architong/config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from apps.common.views import *
from apps.book.views import *
from apps.forum.views import *
from apps.calculator.views import *

# ------ Error Handler ------
handler404 = 'apps.common.views.page_not_found_view'
handler500 = 'apps.common.views.server_error_view'

urlpatterns = [
    # ------ Common ------
    path('', index),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('profile/<str:username>', Profile.as_view()),
    path('wiki/list', wiki_list),
    path('law/list', law_list),
    path('law', LawView.as_view()),
    path('law/<int:book_id>/init', law_edit_init),
    path('law/<int:page_id>', law_manage, name="law_manage"),
    path('user', user_manage),
    path('user/<int:user_id>', user_update),
    path('access-restrict', access_restrict),

    # ------ Book ------
    path('wiki/', wiki_view),
    path('wiki/<int:book_id>', wiki_manage),
    path('wiki/page', wiki_add),
    path('wiki/page/<int:page_id>', wiki_preview),
    path('wiki-editor/<int:book_id>', wiki_page_add),
    path('wiki-editor/page/<int:page_id>', wiki_editor, name="wiki_editor"),
    path('book/<int:book_id>', view_book),
    path('book/bookmark/<int:page_id>', add_or_remove_bookmark),
    path('book/like/<int:book_id>', book_like),
    path('page/<int:page_id>', view_page),
    path('bookmark/', view_bookmark),
    path('bookmark/<int:page_id>', delete_bookmark),
    path('bookmark/label/<int:label_id>', manage_label),

    # ------ Forum ------
    path('comment/<str:id>', CommentView.as_view()),
    path('comment/update/<str:id>', comment_update),
    path('comment/count/', comment_count),
    path('comment/like/<str:comment_id>', like_comment),
    path('forum/', forum),
    path('forum/<str:comment_id>', forum_detail),

    # ------ Calculator ------
    path('calc/uvalue', uvalue),
    path('m.calc/uvalue', uvalue_m),
    path('calc/uvalue/data', uvalue_data),
]

architong/apps/book/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MinLengthValidator


class Books(models.Model):
    book_id = models.AutoField(primary_key=True)
    book_title = models.CharField(max_length=255, validators=[MinLengthValidator(3)])
    author_id = models.CharField(max_length=150)
    cover_path = models.CharField(max_length=255, blank=True, null=True)
    rls_yn = models.CharField(max_length=10)
    like_cnt = models.IntegerField(blank=True, null=True)
    wrt_dt = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    enfc_dt = models.DateTimeField(blank=True, null=True)
    codes_yn = models.CharField(max_length=10, blank=True, null=True)
    mdfcn_dt = models.DateTimeField(auto_now=True)
    hit_count = models.IntegerField(blank=True, null=True, default=0)
    CODE_CHOICES = (
        ('0', '법령'), ('1', '행정규칙'), ('2', '자치법규')
    )
    WIKI_CHOICES = (
        ('0', '전체'), ('1', '설계'), ('2', '재료'), ('3', '시공'),
        ('4', '설비'), ('5', '환경'), ('6', '도시'), ('7', '기타')
    )
    code_gubun = models.CharField(max_length=2, choices=CODE_CHOICES)
    wiki_gubun = models.CharField(max_length=10, blank=True, null=True, choices=WIKI_CHOICES)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='UserLikeBook')

    class Meta:
        managed = False
        db_table = 'books'


class UserLikeBook(models.Model):
    id = models.AutoField(primary_key=True)
    book = models.ForeignKey(Books, models.DO_NOTHING)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING)
    reg_dt = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'user_like_book'


class Pages(models.Model):
    page_id = models.AutoField(primary_key=True)
    book_id = models.IntegerField()
    page_title = models.CharField(max_length=255)
    parent_id = models.IntegerField(blank=True, null=True, default=0)
    depth = models.IntegerField(blank=True, null=True, default=0)
    description = models.TextField(blank=True, null=True)
    wrt_dt = models.DateTimeField(auto_now_add=True)
    mdfcn_dt = models.DateTimeField(auto_now=True)

    class Meta:
        managed = False
        db_table = 'pages'


class BookmarkLabel(models.Model):
    label_id = models.AutoField(primary_key=True)
    label_name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'bookmark_label'


class Bookmark(models.Model):
    bookmark_id = models.AutoField(primary_key=True)
    page_id = models.IntegerField()
    book_id = models.IntegerField()
    username = models.CharField(max_length=150)
    reg_dt = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    label = models.ForeignKey(BookmarkLabel, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'bookmark'

architong/apps/book/forms.py
from django import forms
from .models import Books


class BookForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = ['book_title', 'rls_yn', 'wiki_gubun']

architong/apps/book/views.py
import json
import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse

from apps.forum.models import Comments
from .forms import BookForm
from .models import Books, Pages, Bookmark, BookmarkLabel


# 나의 위키 페이지 렌더링
@login_required(login_url="/account/google/login")
def wiki_view(request):
    username = str(request.user)
    sort = request.GET.get('sort', 'recent')  # 정렬기준 쿼리스트링을 가져온다, 없는 경우 default 등록순
    if sort == 'views':
        docs = Books.objects.filter(codes_yn="N", author_id=username).order_by('-hit_count')
    elif sort == 'registered':
        docs = Books.objects.filter(codes_yn="N", author_id=username).order_by('wrt_dt')
    else:
        docs = Books.objects.filter(codes_yn="N", author_id=username).order_by('-mdfcn_dt')

    # 댓글 객체 좋아요 관련 정보 추가 : is_liked, like_user_count
    for doc in docs:
        like_comment = list(Books.objects.get(book_id=doc.book_id).like_users.all())
        if request.user in like_comment:
            doc.is_liked = "true"
        else:
            doc.is_liked = "false"
        doc.like_user_count = len(like_comment)

    # 페이징처리
    page = request.GET.get('page')
    paginator = Paginator(docs, 15).get_page(page)

    # 정렬기준
    sort_list = [{'value': 'recent', 'label': '최근 편집순'},
                 {'value': 'views', 'label': '조회순'},
                 {'value': 'registered', 'label': '작성순'}]
    if sort != 'recent':
        for idx, item in enumerate(sort_list):
            if item.get('value') == sort:
                sel_item = sort_list[idx]
                sort_list.remove(sel_item)
                sort_list.insert(0, sel_item)
    context = {"books": paginator, "sort_list": sort_list}
    return render(request, "book/wiki_manage.html", context)


# 책만들기 function
@login_required(login_url="/account/google/login")
def wiki_add(request):
    # GET 요청이면 위키 작성 페이지 렌더링
    if request.method == 'GET':
        return render(request, "book/wiki_regist.html")

    # POST 요청이면 위키 저장하고 페이지 에디터로 렌더링
    elif request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            # 신규 book 객체 저장
            new_book = Books(
                author_id=request.user,
                book_title=request.POST.get('book_title'),
                rls_yn=request.POST.get('rls_yn'),
                wiki_gubun=request.POST.get('wiki_gubun'),
                codes_yn="N",
            )
            new_book.save()
            book_id = Books.objects.order_by('book_id').last().book_id

            # 공개위키 작성시 활동점수 +3
            if request.POST.get('rls_yn') == "Y":
                author = get_user_model().objects.get(username=request.user)
                author.act_point = int(author.act_point) + 3
                author.save()

            return JsonResponse({"book_id": book_id})
        else:
            return JsonResponse({"error_message": "책제목은 최소 3글자, 최대 255글자 입니다."})


# 책정보 조회/수정 function
@login_required(login_url="/account/google/login")
def wiki_manage(request, book_id):
    # 위키 쿼리셋
    try:
        book = Books.objects.get(book_id=book_id, codes_yn="N")
    except Books.DoesNotExist:
        return render(request, "404.html", {"message": "존재하지 않는 위키입니다."})

    # 작성자와 사용자가 일치하는지 체크
    if str(request.user) == book.author_id:
        # 위키 조회
        if request.method == 'GET':
            # 목차 계층구조 정렬
            sorted_pages = []
            parent_pages = Pages.objects.filter(book_id=book.book_id, depth=0)
            child_pages = Pages.objects.filter(book_id=book.book_id, depth=1)
            for parent_page in parent_pages:
                sorted_pages.append(parent_page)
                for child_page in child_pages:
                    if child_page.parent_id == parent_page.page_id:
                        sorted_pages.append(child_page)
            # 댓글 객체 좋아요 관련 정보 추가 : is_liked, like_user_count
            like_comment = list(book.like_users.all())
            if request.user in like_comment:
                book.is_liked = "true"
            else:
                book.is_liked = "false"
            book.like_user_count = len(like_comment)
            # 댓글 갯수
            page_list = Pages.objects.filter(book_id=book_id).values_list('page_id')
            comment_count = Comments.objects.filter(page_id__in=page_list).count()
            book.comment_count = comment_count
            context = {"book": book,
                       "page_list": sorted_pages}
            return render(request, "book/editor.html", context)

        # 위키 저장
        elif request.method == 'POST':
            form = BookForm(request.POST)
            if form.is_valid():
                book.book_title = request.POST.get('book_title')
                book.rls_yn = request.POST.get('rls_yn')
                book.wiki_gubun = request.POST.get('wiki_gubun')
                book.save()
                return JsonResponse({"result": "success", "message": "위키정보가 저장되었습니다."})
            else:
                return JsonResponse({"result": "fail", "message": "정보를 확인해주세요."})

        # 위키 삭제
        elif request.method == 'DELETE':
            # 연관 북마크 삭제
            Bookmark.objects.filter(book_id=book_id).delete()
            # 연관 댓글 삭제
            page_list = Pages.objects.filter(book_id=book_id)
            for page in page_list:
                Comments.objects.filter(page_id=page.page_id).delete()
            # 하위 페이지들 삭제
            page_list.delete()
            # 페이지 삭제
            book.delete()
            return JsonResponse({"result": "success"})
    else:
        return render(request, "404.html", {"message": "잘못된 접근입니다."})


# 마크다운 에디터 페이지 추가 function
@login_required(login_url="/account/google/login")
def wiki_page_add(request, book_id):
    # 위키 쿼리셋
    try:
        book = Books.objects.get(book_id=book_id, codes_yn="N")
    except Books.DoesNotExist:
        return render(request, "404.html", {"message": "존재하지 않는 위키입니다."})

    # 작성자와 사용자가 일치하는지 체크
    if str(request.user) == book.author_id:
        # GET 요청이면 editor 새로운 페이지 생성 후 페이지 렌더링
        if request.method == 'GET':
            # 새로운 페이지 등록
            new_page = Pages(
                book_id=book_id,
                parent_id=request.GET.get('page', 0),
                depth=1 if request.GET.get('page') else 0,
                page_title="페이지 제목"
            )
            new_page.save()
            book.mdfcn_dt = datetime.datetime.now().now()
            book.save()  # 해당 위키의 최근수정일 갱신
            new_page = Pages.objects.order_by('page_id').last()
            return HttpResponseRedirect(reverse("wiki_editor", args=[new_page.page_id]))
    else:
        return render(request, "404.html", {"message": "잘못된 접근입니다."})


# 마크다운 에디터 function
@login_required(login_url="/account/google/login")
def wiki_editor(request, page_id):
    # 페이지, 위키 쿼리셋
    try:
        page = Pages.objects.get(page_id=page_id)
        book = Books.objects.get(book_id=page.book_id, codes_yn="N")
    except Pages.DoesNotExist:
        return render(request, "404.html", {"message": "존재하지 않는 페이지입니다."})
    except Books.DoesNotExist:
        return render(request, "404.html", {"message": "존재하지 않는 위키입니다."})

    # 작성자와 사용자가 일치하는지 체크
    if str(request.user) == book.author_id:
        # GET 요청이면 에디터 페이지 랜더링
        if request.method == 'GET':
            # 목차 계층구조 정렬
            sorted_pages = []
            parent_pages = Pages.objects.filter(book_id=book.book_id, depth=0)
            child_pages = Pages.objects.filter(book_id=book.book_id, depth=1)
            for parent_page in parent_pages:
                sorted_pages.append(parent_page)
                for child_page in child_pages:
                    if child_page.parent_id == parent_page.page_id:
                        sorted_pages.append(child_page)
            context = {"page_form": page,
                       "page_id":  page.page_id,
                       "book": book,
                       "page_list": sorted_pages}
            return render(request, 'book/editor.html', context)

        # POST 요청이면 페이지 수정 저장
        elif request.method == 'POST':
            page.page_title = request.POST['page_title']
            page.description = request.POST['description']
            page.save()
            book.mdfcn_dt = datetime.datetime.now().now()
            book.save()     # 해당 위키의 최근수정일 갱신
            return JsonResponse({"page_id": page_id})

        # DELETE 요청이면 페이지 삭제
        elif request.method == 'DELETE':
            # 연관 북마크 삭제
            Bookmark.objects.filter(page_id=page_id).delete()
            # 연관 댓글 삭제
            Comments.objects.filter(page_id=page_id).delete()
            # 자식 페이지 삭제
            Pages.objects.filter(parent_id=page_id).delete()
            # 페이지 삭제
            page.delete()
            # 해당 위키의 최근수정일 갱신
            book.mdfcn_dt = datetime.datetime.now().now()
            book.save()
            return JsonResponse({"book_id": book.book_id})
    else:
        return render(request, "404.html", {"message": "잘못된 접근입니다."})


# 마크다운 에디터 미리보기 모드 function
@login_required(login_url="/account/google/login")
def wiki_preview(request, page_id):
    # 페이지, 위키 쿼리셋
    try:
        page = Pages.objects.get(page_id=page_id)
        book = Books.objects.get(book_id=page.book_id, codes_yn="N")
    except Pages.DoesNotExist:
        return render(request, "404.html", {"message": "존재하지 않는 페이지입니다."})
    except Books.DoesNotExist:
        return render(request, "404.html", {"message": "존재하지 않는 위키입니다."})

    # 작성자와 사용자가 일치하는지 체크
    if str(request.user) == book.author_id:
        # GET 요청이면 미리보기 페이지 랜더링
        if request.method == 'GET':
            # 페이지 계층구조 정렬

architong/templates/book/law_list.html
{% extends 'common/base.html' %}
{% load socialaccount %}
{% load static %}
{% block css %}
    <style>
        .all-answers {
            padding-left: 0px;
            margin-top: 0px;
        }
        h5 {
            display: flex;
            align-items: center;
            margin-bottom: 0px;
        }
    </style>
{% endblock %}
{% block content %}
<section class="doc_tag_area bg_color sec_pad">
    <div class="container">
        <div class="all-answers col-md-12">
            <div class="filter-bar d-flex">
                <h5>건축법규</h5>
                <div class="sort">
                    <select class="custom-select" id="sortBy" onchange="onchangeSort(this.value)">
                        {% for sort in sort_list %}
                        <option value="{{ sort.value }}">{{ sort.label }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div id="docs" class="row blog_grid_tab">
            {% if books %}
            {% for book in books %}
            <div class="col-lg-4 col-sm-6">
                <div class="blog_grid_post shadow-sm wow fadeInUp">
                    <div onclick="location.href='/book/{{ book.book_id }}'" class="grid_post_content">
                        <div class="post_tag">
                            <a>법규</a>
                            <a class="c_blue">{{ book.get_code_gubun_display }}</a>
                        </div>
                        <a>
                            <h4 class="b_title">{{ book.book_title }}</h4>
                        </a>
                        <div class="media post_author">
                            <div class="round_img">
                                {% if book.pictrue %}
                                <img src="{{ book.pictrue }}" alt="">
                                {% else %}
                                <img src="{% static 'img/blog-grid/author_1.jpg' %}" alt="">
                                {% endif %}
                            </div>
                            <div class="media-body author_text">
                                <div class="date">{{ book.enfc_dt | date:'Y.m.d' }} 시행</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p style="margin: auto; padding: 20px 0; color: rgba(0, 0, 0, 0.4);">검색 결과가 없습니다.</p>
            {% endif %}
        </div>
        <div class="col-lg-12 col-sm-2" style="text-align: center">
            <nav class="navigation pagination" style="display: inline;">
                <div class="nav-links" style="padding-top: 50px;">
                    {% if books.has_previous %}
                    <a class="next page-numbers" onclick='onclickPagination("{{ previous_page_number}}")' style="cursor: pointer;"><i class="arrow_carrot-left"></i></a>
                    {% endif %}

                    {% for page_number in books.paginator.page_range %}
                    {% if page_number >= books.number|add:-5 and page_number <= books.number|add:5 %}
                    {% if page_number == books.number %}
                    <a class="page-numbers current" onclick='onclickPagination("{{ page_number}}")' style="cursor: pointer;">{{ page_number}}</a>
                    {% else %}
                    <a class="page-numbers" onclick='onclickPagination("{{ page_number}}")' style="cursor: pointer;">{{ page_number}}</a>
                    {% endif %}
                    {% endif %}
                    {% endfor %}

                    {% if books.has_next %}
                    <a class="next page-numbers" onclick='onclickPagination("{{ next_page_number}}")' style="cursor: pointer;"><i class="arrow_carrot-right"></i></a>
                    {% endif %}
                </div>
            </nav>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}
<script src="{% static 'js/common.js' %}"></script>
{% endblock %}

architong/templates/book/lawlist.html
{% extends 'common/base.html' %}
{% load socialaccount %}
{% load static %}
{% block css %}
    <style>
        .all-answers {
            padding-left: 0px;
            margin-top: 0px;
        }
        h5 {
            display: flex;
            align-items: center;
            margin-bottom: 0px;
        }
        .post_author {
            align-items: center;
        }
        .post_tag {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .post_tag > p {
            margin-bottom: 0px;
            font-size: 14px;
        }
    </style>
{% endblock %}
{% block content %}
<section class="doc_tag_area bg_color sec_pad">
    <div class="container">
        <div class="all-answers col-md-12">
            <div class="filter-bar d-flex">
                <h5>건축법규</h5>
                <div class="sort">
                    <select class="custom-select" id="sortBy" onchange="onchangeSort(this.value)">
                        {% for sort in sort_list %}
                        <option value="{{ sort.value }}">{{ sort.label }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div id="docs" class="row blog_grid_tab">
            {% if books %}
            {% for book in books %}
            <div class="col-lg-4 col-sm-6">
                <div class="blog_grid_post shadow-sm wow fadeInUp">
                    <div onclick="location.href='/book/{{ book.book_id }}'" class="grid_post_content">
                        <div class="post_tag">
                            <div>
                                <a>법규</a>
                                <a class="c_blue">{{ book.get_code_gubun_display }}</a>
                            </div>
                            <p>
                                {% if book.is_liked == "true" %}
                                    <ion-icon name="heart"></ion-icon>&nbsp;{{ book.like_user_count }}&nbsp;&nbsp;
                                {% else %}
                                    <ion-icon name="heart-outline"></ion-icon>&nbsp;{{ book.like_user_count }}&nbsp;&nbsp;
                                {% endif %}
                                <ion-icon name="eye-outline"></ion-icon> {{ book.hit_count }}
                            </p>
                        </div>
                        <a>
                            <h4 class="b_title">{{ book.book_title }}</h4>
                        </a>
                        <div class="media post_author">
                            <div class="round_img">
                                {% if book.pictrue %}
                                <img src="{{ book.pictrue }}" alt="">
                                {% else %}
                                <img src="{% static 'img/blog-grid/author_1.jpg' %}" alt="">
                                {% endif %}
                            </div>
                            <div class="media-body author_text">
                                <div class="date">{{ book.enfc_dt | date:'Y.m.d' }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p style="margin: auto; padding: 20px 0; color: rgba(0, 0, 0, 0.4);">검색 결과가 없습니다.</p>
            {% endif %}
        </div>
        <div class="col-lg-12 col-sm-2" style="text-align: center">
            <nav class="navigation pagination" style="display: inline;">
                <div class="nav-links" style="padding-top: 50px;">
                    {% if books.has_previous %}
                    <a class="next page-numbers" onclick='onclickPagination("{{ previous_page_number}}")' style="cursor: pointer;"><i class="arrow_carrot-left"></i></a>
                    {% endif %}

                    {% for page_number in books.paginator.page_range %}
                    {% if page_number >= books.number|add:-5 and page_number <= books.number|add:5 %}
                    {% if page_number == books.number %}
                    <a class="page-numbers current" onclick='onclickPagination("{{ page_number}}")' style="cursor: pointer;">{{ page_number}}</a>
                    {% else %}
                    <a class="page-numbers" onclick='onclickPagination("{{ page_number}}")' style="cursor: pointer;">{{ page_number}}</a>
                    {% endif %}
                    {% endif %}
                    {% endfor %}

                    {% if books.has_next %}
                    <a class="next page-numbers" onclick='onclickPagination("{{ next_page_number}}")' style="cursor: pointer;"><i class="arrow_carrot-right"></i></a>
                    {% endif %}
                </div>
            </nav>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}
<script src="{% static 'js/common.js' %}"></script>
{% endblock %}

architong/templates/book/wiki_manage.html
{% extends 'common/base.html' %}
{% load socialaccount %}
{% load static %}

{% block css %}
    <style>
        .all-answers {
            padding-left: 0px;
            margin-top: 0px;
        }
        h5 {
            display: flex;
            align-items: center;
            margin-bottom: 0px;
        }
        .post_author {
            align-items: center;
        }
        #add_wiki {
            font-size: 15px;
            font-weight: bolder;
        }
        .post_tag {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .post_tag > p {
            margin-bottom: 0px;
            font-size: 14px;
        }
    </style>
{% endblock %}

{% block content %}
<div class="breadcrumb_area_three" style="padding: 0"></div>
<section class="doc_tag_area bg_color sec_pad">
    <div class="container">
        <div class="all-answers col-md-12">
            <h5>{{ request.user.first_name }}님의 위키</h5><hr>
            <div class="filter-bar d-flex" style="align-items: center;">
                <div class="sort">
                    <select class="custom-select" id="sortBy" onchange="onchangeSort(this.value)">
                        {% for sort in sort_list %}
                        <option value="{{ sort.value }}">{{ sort.label }}</option>
                        {% endfor %}
                    </select>
                </div>
                <a href="/wiki/page" id="add_wiki"><i class=" icon_folder-add_alt"></i>&nbsp;&nbsp;새 위키 작성</a>
            </div>
        </div>
        <div id="docs" class="row blog_grid_tab">
            {% if books %}
            {% for book in books %}
            <div class="col-lg-4 col-sm-6">
                <div class="blog_grid_post shadow-sm wow fadeInUp">
                    <div onclick="location.href='/wiki/{{ book.book_id }}'" class="grid_post_content">
                        <div class="post_tag">
                            <div>
                                <a href="javascript:;">위키</a>
                                {% if book.wiki_gubun %}
                                <a class="c_blue">{{ book.get_wiki_gubun_display }}</a>
                                {% endif %}
                            </div>
                            <p>
                                {% if book.is_liked == "true" %}
                                    <ion-icon name="heart"></ion-icon>&nbsp;{{ book.like_user_count }}&nbsp;&nbsp;
                                {% else %}
                                    <ion-icon name="heart-outline"></ion-icon>&nbsp;{{ book.like_user_count }}&nbsp;&nbsp;
                                {% endif %}
                                <ion-icon name="eye-outline"></ion-icon> {{ book.hit_count }}
                            </p>
                        </div>
                        <a>
                            <h4 class="b_title">{{ book.book_title }}</h4>
                        </a>
                        <div class="media post_author">
                            <div class="round_img">
                                {% if book.pictrue %}
                                <img src="{{ book.pictrue }}" alt="">
                                {% else %}
                                <img src="{% static 'img/blog-grid/author_1.jpg' %}" alt="">
                                {% endif %}
                            </div>
                            <div class="media-body author_text">
                                <h4>{{ book.author_id }}</h4>
                                <div class="date">최근 편집&nbsp;&nbsp;{{ book.mdfcn_dt | date:'Y.m.d' }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p style="margin: auto; padding: 20px 0; color: rgba(0, 0, 0, 0.4);">등록된 위키가 없습니다.</p>
            {% endif %}
        </div>
        <div class="col-lg-12 col-sm-2" style="text-align: center">
            <nav class="navigation pagination" style="display: inline;">
                <div class="nav-links" style="padding-top: 50px;">
                    {% if books.has_previous %}
                    <a class="next page-numbers" onclick='onclickPagination("{{ previous_page_number}}")' style="cursor: pointer;"><i class="arrow_carrot-left"></i></a>
                    {% endif %}
                    {% for page_number in books.paginator.page_range %}
                    {% if page_number >= books.number|add:-5 and page_number <= books.number|add:5 %}
                    {% if page_number == books.number %}
                    <a class="page-numbers current" onclick='onclickPagination("{{ page_number}}")' style="cursor: pointer;">{{ page_number}}</a>
                    {% else %}
                    <a class="page-numbers" onclick='onclickPagination("{{ page_number}}")' style="cursor: pointer;">{{ page_number}}</a>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    {% if books.has_next %}
                    <a class="next page-numbers" onclick='onclickPagination("{{ next_page_number}}")' style="cursor: pointer;"><i class="arrow_carrot-right"></i></a>
                    {% endif %}
                </div>
            </nav>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}
<script src="{% static 'js/common.js' %}"></script>
{% endblock %}